//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Проект_турникеты_А
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Gimnazia1Entities : DbContext
    {
        public Gimnazia1Entities()
            : base("name=Gimnazia1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<pList> pList { get; set; }
        public virtual DbSet<pLogData> pLogData { get; set; }
        public virtual DbSet<pMark> pMark { get; set; }
    }
}
